s = "Hello World, how are you?"
s2 = s.split(' ')
print(" ")
print("s = ", s)
print(" ")
print("s2 = s.split > ", s2)
s3 = '#'.join(s2)
print(" ")
print("s3 = s2.join# > ", s3)
print(" ")
s4 = s.replace(' ', '**')
print("s4 = s.replace > ", s4)
print(" ")
s5 = s.partition(' ')
print("s5 = s.partition > ", s5)
print(" ")
s6 = s.rpartition(' ')
print("s6 = s.rpartition > ", s6)
